### PR TITLE
Update php-giantbomb with fixes and slight changes.

### PR DESCRIPTION
**Pull request by DariusIII**

### CODE REVIEW

**Comment by dborsatto** [comment]
Hi, first of all, thanks for taking the time of contributing!

I have a few comments:
- YAML removal and CacheProvider renaming: thanks, I missed that.
- In the Client constructor, why setting `$config` as optional by giving it a default value of `null`? I don't see the point to be honest, if there is no configuration, then the whole library will not work.
- About the PHPDocs, there is an overall alignment problem. As you can see for instance in [Symfony](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php) or [Laravel](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Container/Container.php), the convention is to have 4 spaces before `/**` in the first line, and then the subsequent lines start with 5 spaces.
- Another stylistic issue in the PHPDocs is using the FQCN in the return type. Technically [there is no reason to that](https://phpdoc.org/docs/latest/guides/types.html), and especially considering that in this simple library all classes live in the same namespace, I think the way it is now is a bit cleaner and less cluttered.
- +1 for the `@throws` annotation.
- In the `Model` class, you added `__set()`. I'm not sure about because 1) you have an `echo` inside it (maybe a leftover from debugging) 2) GiantBomb's API is read-only. This means that after the API results are hydrated in the constructor, adding a possibility to change those values would be going against the fact that a `Model` is a static representation of an API call object. Being immutable in this case is by design, because it's a read-only API.

Overall there are a few things which I will integrate in the library (fixes, typos, using `===` instead of `==`), but  because of the aforementioned problems, I can't merge this PR as-is.

**Comment by DariusIII** [comment]
- $config null value - You  already had it set in @var declaration was already set as $config = null (https://github.com/dborsatto/php-giantbomb/blob/master/src/Client.php#L28)

- PHPdocs were auto-generated by PHPStorm, but that is actualy my setup that does that

- Fully qualified names can be reverted

- __set can also be removed, as i have added it because of getters in the API.

Anyway, you can change the php-giantbomb with some of my fixes, but also please add __isset to Model so  isset/empty checks can be performed properly.

**Comment by dborsatto** [comment]
I define values like `$config = null` mostly because of stylistic reasons, unrelated to them being optional parameters or not. :-)

I will definitely add `__isset()`. I'm actually doing it right now. For the moment I will close this PR, but I will make the changes and release an updated version later today 👍

**Comment by dborsatto** [comment]
I've released v1.0.2 with some bugfixes and __isset() support.

**Comment by DariusIII** [comment]
Great! Thank you!

**Pull request closed without merging**
